@baseUrl = http://localhost:8080
@contactId = REPLACE_WITH_ID

### Get all contacts
GET {{baseUrl}}/contacts

### Get one contact
GET {{baseUrl}}/contacts/{{contactId}}

### Create contact 
POST {{baseUrl}}/contacts
Content-Type: application/json

{
    "firstName": "Awuah",
    "lastName": "Dennis",
    "email": "awuahdennis20@gmail.com",
    "favoriteColor": "blue",
    "birthday": "1999-06-07"
}

### Update contact
PUT {{baseUrl}}/contacts/{{contactId}}
Content-Type: application/json

{
    "firstName": "Awuah",
    "lastName": "Dennis",
    "email": "awuahdennis20@gmail.com",
    "favoriteColor": "blue",
    "birthday": "1999-06-07"
}

### Delete contact
DELETE {{baseUrl}}/contacts/{{contactId}}

### Invalid contact ID
GET {{baseUrl}}/contacts/not-an-object-id

### Missing required field
POST {{baseUrl}}/contacts
Content-Type: application/json

{
    "firstName": "Incomplete"
}

### Invalid email
POST {{baseUrl}}/contacts
Content-Type: application/json

{
    "firstName": "Awuah",
    "lastName": "Dennis",
    "email": "not-an-email",
    "favoriteColor": "blue",
    "birthday": "1999-06-07"
}

### Invalid birthday format
POST {{baseUrl}}/contacts
Content-Type: application/json

{
  "firstName": "Awuah",
  "lastName": "Dennis",
  "email": "awuahdennis20@gmail.com",
  "favoriteColor": "blue",
  "birthday": "07/06/1999"
}

### Nonexistent valid ID
GET {{baseUrl}}/contacts/64f0d7c5d4d27b4f1a1b2c3d